config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  get 'information/NormasAPA'
  get '/booksearch', to: 'booksearch#search', as: :booksearch_path

  root 'reference_generator#index'
  resources :references
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  isbn       :string
#  title      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ApplicationRecord
  belongs_to :user
end

app/models/reference.rb
# == Schema Information
#
# Table name: references
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  year             :integer
#  title            :string
#  subtitle         :string
#  publicationPlace :string
#  editorial        :string
#  pageNumber       :integer
#  referencedText   :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  authorName       :string
#  authorLastName   :String
#

class Reference < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable
  has_many :references
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :user_id)
    end
end

app/controllers/booksearch_controller.rb
class BooksearchController < ApplicationController
    include HTTParty
    base_uri "https://www.googleapis.com/books/v1/"
    
    def search
        #self.class.get('/volumes?q=cien anos de soledad')

        #url = 'https://www.googleapis.com/books/v1/volumes?q=el zahir'
        url = 'https://www.googleapis.com/books/v1/volumes?q='+params[:search]
        
        response = HTTParty.get(url, :verify => false)
        @response = JSON.parse(response.body)['items']
    end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def NormasAPA
  end

  def ListasyFiguras
  end

  def Citas
  end

  def Referencias
  end
end

app/controllers/reference_generator_controller.rb
class ReferenceGeneratorController < ApplicationController
  layout 'application', :except => :action
  layout "main", :only => :index
  
  def index
  end

  def new
    @reference = Reference.new
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = current_user.references
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = current_user.references.build
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = current_user.references.build(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:user_id, :year, :title, :subtitle, :publicationPlace, :editorial, :pageNumber, :authorName, :authorLastName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/booksearch_helper.rb
module BooksearchHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/reference_generator_helper.rb
module ReferenceGeneratorHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :book_isbn %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :book_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.user %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @book.user %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/booksearch/search.html.erb
<% @response.each do |reference| %>
    <div class="item_container row">
        <div class="col-auto">
            <% if !reference['volumeInfo']['imageLinks'].nil? %>
                <img src="<%= reference['volumeInfo']['imageLinks']['thumbnail'] %>">
            <% end %>
        </div>
        <div class="col">
            <% if !reference['volumeInfo']['title'].nil? %>
                <h5>
                    <%= reference['volumeInfo']['title'] %>
                </h5>
            <% end %>
            <% if !reference['volumeInfo']['authors'].nil? %>
                <p>
                    Autor(es):
                    <% reference['volumeInfo']['authors'].each_with_index do |author,i| 
                        temp=""
                        if i+2<reference['volumeInfo']['authors'].length then
                            temp=","
                        elsif i+2==reference['volumeInfo']['authors'].length then
                            temp=" &"
                        end
                        %>
                        <%=author%><%=temp%>
                    <% end %>
                </p>
            <% end %>
            <p>
                Editorial:
                <% if !reference['volumeInfo']['publisher'].nil? %>
                    <%=reference['volumeInfo']['publisher']%>
                <% else %>
                    n/a
                <% end %>
                <% if !reference['volumeInfo']['publishedDate'].nil? %>
                    en: <%=reference['volumeInfo']['publishedDate']%>
                <% end %>
            </p>
            <p style="text-align:justify">
                <% if !reference['volumeInfo']['description'].nil? %>
                    <%=reference['volumeInfo']['description']%>
                <% end %>
            </p>
            <hr>
            





            <% if !reference['volumeInfo']['authors'].nil? %>
                <% reference['volumeInfo']['authors'].each_with_index do |author, i| %>
                    <%
                        temp=""
                        if i+2<reference['volumeInfo']['authors'].length then
                            temp=","
                        elsif i+2==reference['volumeInfo']['authors'].length then
                            temp=" &"
                        end

                        a=author.split(/( )/)
                        sliced = a[1..-1].each_slice(2).map(&:join)
                        final = [a[0]] + sliced
                        if final.length == 2 then
                            nombre=final[0][0,1]
                            apellido=final[1]
                        end
                        if final.length > 2 then
                        nombre=final[0][0,1]
                        apellido=final[2]
                    end
                    %>
                    <%=apellido%>, <%=nombre%>.<%=temp%>
                <% end %>
            <% else %>
                Anónimo.
            <% end %>

            <% if !reference['volumeInfo']['publishedDate'].nil? %>
                (<%=reference['volumeInfo']['publishedDate'][0,4]%>).
            <% else %>
                (s.f.).
            <% end %>
            <i>
            <% if !reference['volumeInfo']['title'].nil? %>
                <%= reference['volumeInfo']['title']%>.
            <% end %>
            </i>
            <% if !reference['volumeInfo']['publisher'].nil? %>
                <%=reference['volumeInfo']['publisher']%>.
            <% end %>



        </div>
    </div>
    <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApaHelp</title>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="wrapper">
      <div class="row" style="padding-top:100px; padding-bottom:50px;">
        <div class="col-11 col-lg-8 mx-auto">
          <%= yield %>
        </div>
      </div>
      <div class="push"></div>
    </div>
    



    <footer class="footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © CodeArt 2018</small>
        </div>
      </div>
</footer>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApaHelp</title>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="wrapper">
      <%= yield %>
      <div class="push"></div>
    </div>
    



     <footer class="footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © CodeArt 2018</small>
        </div>
      </div>
</footer>
  </body>
  
</html>

app/views/reference_generator/index.html.erb
<!--parallax 1 -->
<section class="bg-1">
    <h1 class="text-center" style="margin-top:120px;">Generador de referencias</h1>
        <%= form_tag(booksearch_path_url, :method => 'get') do %>    
            <div class="input-group col-8 mx-auto">
                <%= text_field_tag :search, params[:search], class: 'form-control' %>
                <div class="input-group-append">
                    <%= submit_tag("Buscar", :class=>"btn btn-secondary") %>
                </div>
            </div>
        <% end %>
        <div class="col-8 mx-auto">
            <a href="references/new">Generar referencia a mano</a>
        </div>
</section>
<!--/parallax 1-->


<div class="row">
    <div class="col-lg-8 mx-auto">
        <div class="container">

            <hr>

            <div class="row">
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Tablas y Figuras</h3>
                        </div>
                        <div class="panel-body text-justify">Cualquier forma de presentación empleada en un trabajo tendrá que ser
                                                denominada Tabla o Figura. Según las normas APA, “generalmente las tablas exhiben valores
                                                numéricos exactos y los datos están dispuestos de forma organizada en
                                                líneas y columnas, facilitando su comparación". Y las figuras son “cualquier tipo de 
                                                ilustración que no sea tabla. Una figurapuede ser un cuadro, un gráfico, una fotografía, 
                                                un dibujo u otra forma de representación”. 
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Citas</h3>
                        </div>
                        <div class="panel-body text-justify">Una cita es la expresión parcial de ideas o afirmaciones incluidas en un texto con referencia precisa
                                                            de su origen o fuente y la consignación dentro de la estructura del texto. En el estilo APA se utilizan
                                                            paréntesis dentro del texto en lugar de notas al pie de página o al final del texto, como en otros
                                                            estilos. La cita ofrece información sobre el autor y año de publicación, que conduce al lector a las
                                                            referencias que se deben consignar al final del documento que se esta utilizando la cita. 
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Referencias</h3>
                        </div>
                        <div class="panel-body text-justify">Las referencias son un listado con la información completa de las fuentes citadas en el texto, que
                                                            permite identificarlas y localizarlas para cerciorarse de la información contenida allí o complementarla,
                                                            en caso de ser necesario. En la lista de referencias, el autor incluye solo aquellas fuentes que utilizó en su trabajo. En este
                                                            sentido, “una lista de referencias cita trabajos que apoyan específicamente a un artículo en particular.
                        </div>
                    </div>
                </div>
            </div>
            <!--/row-->

            <hr>

        </div>
    </div>
</div>
<!--/container-->

<div class="divider"></div>

<section class="bg-2 text-center">
        <h1>Rapido y facil de usar</h1>
</section>

<div class="divider"></div>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>IDEA</h3>
                </div>
                <div class="panel-body text-justify">ApaNica es un sitio Web de ayuda para los estudiantes que tienen problemas con las molestas pero
                                        necesarias normas APA, aqui los ayudaremos con información y generadores para referencias,
                                        ademas de eso, a traves de esta aplicación puedes tener acceso a los libros de google books que tambien puedes referenciar 
                                        de la forma correcta. 

                </div>
            </div>
        </div>
    </div>
</div>
<!--/container-->

<div class="divider"></div>

<!--parallax 2 -->
<section class="bg-3 text-center">
    <h1>Las Normas APA pueden ser divertidas</h1>
    <p class="lead"></p>
</section>
<!--/parallax 2-->

<script>
    (function ($) {

        $.fn.parallax = function (options) {

            var windowHeight = $(window).height();

            // Establish default settings
            var settings = $.extend({
                speed: 0.15
            }, options);

            // Iterate over each object in collection
            return this.each(function () {

                // Save a reference to the element
                var $this = $(this);

                // Set up Scroll Handler
                $(document).scroll(function () {

                    var scrollTop = $(window).scrollTop();
                    var offset = $this.offset().top;
                    var height = $this.outerHeight();

                    // Check if above or below viewport
                    if (offset + height <= scrollTop || offset >= scrollTop + windowHeight) {
                        return;
                    }

                    var yBgPosition = Math.round((offset - scrollTop) * settings.speed);

                    // Apply the Y Background Position to Set the Parallax Effect
                    $this.css('background-position', 'center ' + yBgPosition + 'px');

                });
            });
        }
    }(jQuery));

    $('.bg-1,.bg-3').parallax({
        speed: 0.15
    });

    $('.bg-2').parallax({
        speed: 0.25
    });

</script>

app/views/references/_form.html.erb
<%= form_with(model: reference, local: true) do |form| %>

  <div class="content-wrapper">
    <div class="container-fluid">

      <% if reference.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>
    
        <ul>
        <% reference.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <!--div class="field col-sm-6 col-md-3">
      <%= form.label :user_id %> <br>
      <%= form.text_field :user_id, id: :reference_user_id %>
    </div-->

      <hr class="mt-2">
      
        <div class="item_container card-body">
          <form class="form" action="">
            <div class="row">
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Año:" %> <br>
                <%= form.text_field :year, id: :reference_year, class: 'form-control' %>
              </div>
              
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Título:" %> <br>
                <%= form.text_field :title, id: :reference_title, class: 'form-control' %>
              </div>
              
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Subtítulo:" %> <br>
                <%= form.text_field :subtitle, id: :reference_subtitle, class: 'form-control' %>
              </div>
              
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Lugar de Publicación:" %> <br>
                <%= form.text_field :publicationPlace, id: :reference_publicationPlace, class: 'form-control' %>
              </div>
              
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Editorial:" %> <br>
                <%= form.text_field :editorial, id: :reference_editorial, class: 'form-control' %>
              </div>
              
              <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Apellido:" %> <br>
                <%= form.text_field :authorLastName, id: :reference_authorLastName, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group col-sm-6 col-md-4">
                <%= form.label "Inicial del Autor:" %> <br>
                <%= form.text_field :authorName, id: :reference_authorName, class: 'form-control' %>
              </div>
              <div class="form-group row">
                  <div class="col-6 col-md-3"><button type="submit" class="btn btn-block btn-success">Guardar</button></div>
                  <div class="col-6 col-md-3"><button type="reset" class="btn btn-block btn-danger">Cancelar</button></div>
                  <div class="col-6 col-md-3"><%= link_to 'Back', references_path %></div>
             </div>
            
            </div>
          </form>
        </div>
    </div>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> 
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>
<div class="item_container">
<h1>Referencias</h1>

<table id="dataTable" class="table table-hover" cellspacing="0">
  <thead>
  
    <tr>
      <th scope="col">Inicial</th>
      <th scope="col">Apellido</th>
      <th scope="col">Año</th>
      <th scope="col">Título</th>
      <th scope="col">Lugar de Publicación</th>
      <th scope="col">Editorial</th>
      <th scope="col">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <!--td><%= reference.user.email %></td-->
        <td><%= reference.authorName %></td>
        <td><%= reference.authorLastName %></td>
        <td><%= reference.year %></td>
        <td><%= reference.title %></td>
        <td><%= reference.publicationPlace %></td>
        <td><%= reference.editorial %></td>
        <td>
          <%= link_to 'Ver', reference %>
          |
          <%= link_to 'Editar', edit_reference_path(reference) %>
          |
          <%= link_to 'Eliminar', reference, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

</div>

app/views/references/new.html.erb
<h1>Referencia</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<div class="item_container">
<p id="notice"><%= notice %></p>

<p>
    <strong>Inicial:</strong>
    <%= @reference.authorName %>
</p>

  <p>
      <strong>Apellido:</strong>
      <%= @reference.authorLastName %>
  </p>

<p>
  <strong>Year:</strong>
  <%= @reference.year %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reference.title %>
</p>

<p>
  <strong>Publicationplace:</strong>
  <%= @reference.publicationPlace %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @reference.editorial %>
</p>

<p>
  <strong>Pagenumber:</strong>
  <%= @reference.pageNumber %>
</p>

<h2>Referencia</h2>
<p>
  <%= @reference.authorLastName%>, <%= @reference.authorName%> (<%= @reference.year %>).
  <i>
      <%= @reference.title %>.
  </i>
  <%= @reference.publicationPlace %>:<%= @reference.editorial %>.

</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="/">ApaNica</a>
            <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                &#9776;
            </button>
            <div class="collapse navbar-collapse" id="exCollapsingNavbar">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a href="/references/new" class="nav-link">Generador</a></li>
                    <li class="nav-item"><a href="/libros" class="nav-link">Libros</a></li>
                    <li class="nav-item"><a href="/information/NormasAPA" class="nav-link">Información</a></li>
                    <!--
                    <%= notice %>
                    <%= alert %>
                    -->
                </ul>
                <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                    <% if user_signed_in? %>
                        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class=>"nav-link"%>
                    <% else %>
                        <%= link_to "Registrarme", new_user_registration_path, :class=>"nav-link" %>
                        <%= link_to "Iniciar Sesión", new_user_session_path, :class=>"nav-link" %>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>